### ISSUE TITLE
[Issue] Color picker doesn't copy transparency values

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#230] opened 2019-01-26 17:20 UTC
Color picker doesn't copy transparency values.
https://youtu.be/D4MWwvXyb6I

Using: Win10 Blockbench 2.3.2

**Comment by JannisX11** [comment] 2019-02-03 20:48
Fixed in 2.4.

**Closed by JannisX11** 2019-02-03 20:48 UTC

**Comment by TobyMinceraft** [comment] 2020-10-24 23:35
Unless I'm misunderstanding something, I can also confirm this happens in version 3.6.6 (according to the "About" tab, this is the latest version).

What I Expect
1. Use the eyedropper to pick the transparent color/texture
2. Click the paintbrush
3. Begin "painting" with the new color and expect it to be deleted.

If this is not a bug and working as intended, then I apologize for replying to an old post and I can delete this and instead reference this issue in my own. If that's the case, then I would like to see the color picker keep transparency when clicking a transparent cube in the painting area, so that way we can also replace all of that one color with transparency instead of manually deleting it with the eraser tool.
