### ISSUE TITLE
[Suggestion] Allow adding blockbench project models to existing model

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#365] opened 2019-07-17 21:52 UTC
Allow adding blockbench project models to existing model

![image](https://user-images.githubusercontent.com/44243757/61414294-48e68980-a8f6-11e9-92c0-b38670224ae8.png)

**Comment by JannisX11** [comment] 2020-03-10 19:30
Duplicate of #482

**Closed** 2020-03-10 19:30 UTC
