### ISSUE TITLE
pixel rotations

### ISSUE THREAD

**Issue by Grapes-purple** [JannisX11/blockbench#2497] opened 2024-10-02 10:13 UTC
### **ability to rotate a sprite with pivot point, following video has a good reference**
![image](https://cdn.discordapp.com/attachments/1123475784632389642/1289982877269884959/rotate-handles.gif?ex=66fe196c&is=66fcc7ec&hm=da239caed7c43a8d25060bef8c58f7b582b905700f5485e59831b1f7a696bad7&)

**Comment by JannisX11** [comment] 2024-10-03 20:23
Duplicate of #2276

**Closed by JannisX11** 2024-10-03 20:23 UTC
