### ISSUE TITLE
[Suggestion] Add UV overlayi

### ISSUE THREAD

**Issue by Kris2031** [JannisX11/blockbench#1555] opened 2022-09-04 11:22 UTC
Add the uv overlay button to the uv menu in the edit tab
![obraz_2022-09-04_132239803](https://user-images.githubusercontent.com/96983375/188310765-458074f6-110d-4b4f-ad74-86966eaea9a4.png)

**Comment by JannisX11** [comment] 2022-09-04 17:08
Duplicate of #1545

**Closed by JannisX11** 2022-09-04 17:08 UTC
