### ISSUE TITLE
[Issue] Selection outline disappears in some viewing angles

### ISSUE THREAD

**Issue by Gamebuster19901** [JannisX11/blockbench#191] opened 2018-11-27 18:23 UTC
Information:
- When one of my cubes is selected, the wireframe does not appear around it. It does not matter if the cube was selected as a group or selected individually. The cube indicated by the red arrow in the image below is the cube without the wireframe. I have also provided the model below, The specific cube in question has been named "cube_wireframe_problem" in the provided model file.
- Version: Desktop 2.1.0
- Operating System: Windows

- Model: [assault_rifle_bullet.zip](https://github.com/JannisX11/blockbench/files/2621325/assault_rifle_bullet.zip)

![image](https://user-images.githubusercontent.com/7155747/49102489-f95c2c00-f246-11e8-9e48-e3d3bb9f9371.png)

**Comment by Drc-DEV** [comment] 2018-12-03 20:59
Happens more frequently when using "origin to geometry" @JannisX11 If you are unable to reproduce it, just try using origin to geometry on a cube. The wireframe does not show when the zoom is close to the object, and reappears when zooming out. (This problem I experienced on the Desktop Version)

**Comment by JannisX11** [comment] 2018-12-27 14:04
Fixed in 2.3.

**Closed by JannisX11** 2018-12-27 14:04 UTC
