### ISSUE TITLE
blockbench screen for modeling bug instead it goes to the bottom corner Phone I am using = HUAWEI NOVA 2 Lite

### ISSUE THREAD

**Issue by LittlePrinces001** [JannisX11/blockbench#2585] opened 2024-12-14 14:12 UTC
### What are you trying to do, and what do you expect to happen?

I don't do anything and I just want to do modelling 

### What happens instead?

The screen is under the the corner so I can't make a model

### Model format in which the issue occurs

App And Blockbench Web

### Blockbench variant

Website

### Blockbench version

4.1.1.2

### Operating System

Android 

### Installed Blockbench plugins

Nothing

**Comment by LittlePrinces001** [comment] 2024-12-14 14:13
![Uploading IMG-20241214-WA0613.jpg…]()

**Comment by JannisX11** [comment] 2024-12-14 19:28
Is it this issue? https://github.com/JannisX11/blockbench/issues/2444

**Comment by LittlePrinces001** [comment] 2024-12-14 23:01
Yes

**Comment by JannisX11** [comment] 2024-12-15 13:35
Duplicate of #2444

**Closed by JannisX11** 2024-12-15 13:35 UTC

**Comment by LittlePrinces001** [comment] 2024-12-15 13:50
But The Blockbench Work On Mam 😡
