### ISSUE TITLE
Release a .apk on F-Droid and in releases for Android

### ISSUE THREAD

**Issue by RustoMCSpit** [JannisX11/blockbench#2067] opened 2023-10-23 15:04 UTC
### Detailed description of your suggestion

There's a webapp but a .apk is more ideal

**Comment by JannisX11** [comment] 2023-11-30 13:43
Duplicate of #1187

**Closed by JannisX11** 2023-11-30 13:43 UTC
Labels: suggestion

**Comment by RustoMCSpit** [comment] 2023-11-30 14:23
not a duplicate, having a native app ≠ uploading a .apk to f droid

**Comment by RustoMCSpit** [comment] 2023-11-30 14:24
please re-open

**Comment by RustoMCSpit** [comment] 2023-11-30 23:52
> while this is technically not a duplicate issue, blockbench does not seem to have an android native release, therfore, this could be seen as asking for a native release.

this is an issue relevent to another issue then, different issues though. re-open please
