### ISSUE TITLE
Snap bezier handles

### ISSUE THREAD

**Issue by AxlDeBelg** [JannisX11/blockbench#2212] opened 2024-02-26 18:21 UTC
### Detailed description of your suggestion

Is it possible to ‘snap’ bezier handles when pressing down shift? Like when drawing a vector in Adobe Illustrator with the pen tool.

**Comment by JannisX11** [comment] 2024-02-27 07:58
Duplicate of #1757

**Closed by JannisX11** 2024-02-27 07:58 UTC
