### ISSUE TITLE
poly_mesh bones

### ISSUE THREAD

**Issue by wuweixingtian** [JannisX11/blockbench#617] opened 2020-05-05 06:19 UTC
The new "poly_mesh" model can produce more detailed models than the previous "cubes", and it is recommended to add support for this model

**Comment by wuweixingtian** [comment] 2020-05-05 06:22
Converting to the poly_mesh model using the obj file requires little modification

**Comment by iWackyMinecraft** [comment] 2020-05-05 11:23
You can convert OBJ:s to bedrock poly mesh with Bridge
https://github.com/bridge-core/bridge./releases/tag/v1.5.0

**Comment by JannisX11** [comment] 2020-05-06 17:41
Duplicate of #555

**Closed by JannisX11** 2020-05-06 17:41 UTC
