### ISSUE TITLE
texture not shown on screen

### ISSUE THREAD

**Issue by amuhz** [JannisX11/blockbench#2105] opened 2023-11-20 21:51 UTC
### What are you trying to do, and what do you expect to happen?

on opening a blockbench file, i was expecting to have my models shown on my screen.

### What happens instead?

since two days ago, when i open a blockbench file or creating a new one, i only got an empty space without even the base zone at its center. i can only see the models when the view mode is on "solid".
![Screenshot from 2023-11-20 22-43-00](https://github.com/JannisX11/blockbench/assets/138972690/bb0ccf76-baa9-4829-8942-2f28b8f65329)
![Screenshot from 2023-11-20 22-43-21](https://github.com/JannisX11/blockbench/assets/138972690/06eaedde-23bd-4077-a1ef-3e9e485741b3)

### Model format in which the issue occurs

.bbmodel

### Blockbench variant

Program

### Blockbench version

4.8.3 from flathub

### Operating System

Linux, Ubuntu 22.04.3 LTS 64-bit

### Installed Blockbench plugins

minecraft title generator, vintage story models

**Comment by JannisX11** [comment] 2023-11-20 21:57
Duplicate of https://github.com/JannisX11/blockbench/issues/1964

**Closed by JannisX11** 2023-11-20 21:57 UTC

**Comment by amuhz** [comment] 2023-11-20 22:09
a small update for this issue report, it happens that some of my models, the one from the plugin "minecraft title generator" aren't affected by the invisible texture.
![Screenshot from 2023-11-20 23-08-28](https://github.com/JannisX11/blockbench/assets/138972690/4bf58b38-665b-47c8-ba09-695a8e121e25)
