### ISSUE TITLE
[Issue] Spacebar selects colorpicker on paint mode even though it has no keybind

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#647] opened 2020-06-02 16:33 UTC
Spacebar selects colorpicker on paint mode even though it has no keybind.

or is it supposed to toggle between paint & color picker? which doesn't work

Blockbench 3.5.4

**Comment by JannisX11** [comment] 2020-06-02 19:10
Space is by default assigned to "Toggle Tools", which essentially switches to the "alt tool", the tool that gets selected while you hold Alt. This does not necessarily mean that it switches back when you press it again, since that tool can have a different or no alt tool. So sort of works as intended, it's mostly there to switch between the transform tools (move/resize, rotate/pivot).

**Closed by JannisX11** 2020-06-02 19:10 UTC
