### ISSUE TITLE
[Suggestion] support for older graphics cards

### ISSUE THREAD

**Issue by Tokedge** [JannisX11/blockbench#1676] opened 2022-12-03 14:18 UTC
Why not add support for older video cards?

**Comment by Art-bor** [comment] 2022-12-26 11:48
it already supports even the most basic video cards
for example intel hds and integrated gpus they work perfectly fine
and if you meant old nvidia gpus 
if Nvidia stopped support for them there is no point in addind support to them in blockbench

**Comment by JannisX11** [comment] 2023-01-10 15:52
Duplicate of #1617
(Answered there)

**Closed by JannisX11** 2023-01-10 15:52 UTC

**Comment by binugamez** [comment] 2023-01-12 15:07
ow man
