### ISSUE TITLE
[Suggestion] Render the background image over the ground plane

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1243] opened 2022-01-01 15:00 UTC
![bg_image_behind_ground](https://user-images.githubusercontent.com/81629481/147853468-4134e939-5642-4846-83a0-a1109f4c2f60.gif)

**Comment by Wackyblocks** [comment] 2022-01-01 18:42
Duplicate of #1238

**Comment by JannisX11** [comment] 2022-01-05 21:46
The ground is part of the scene, and can also cover parts of your model. If background images would render over the ground, that means they would also render over parts of your model. Also, the ground plane couldn't be used in combination with backgrounds because it would often be hidden behind them.
If you want to see the background, don't enable the ground. If you have a reference image that you want to see above your 3D scene, use PureRef.

**Closed by JannisX11** 2022-01-05 21:46 UTC
