### ISSUE TITLE
Move Layer tool cannot be removed from hotbar in paint mode

### ISSUE THREAD

**Issue by TheIsopodManiac** [JannisX11/blockbench#2581] opened 2024-12-11 02:47 UTC
### What are you trying to do, and what do you expect to happen?

I am removing the move layer tool in paint mode, and I expect it to stay gone.

### What happens instead?

It comes back after closing and opening Blockbench, no matter what.

### Model format in which the issue occurs

Generic Model is the only format I use

### Blockbench variant

Program

### Blockbench version

4.11.2

### Operating System

What does this mean, Windows, I guess?

### Installed Blockbench plugins

Minecraft Title Generator, Minecraft Entity Wizard, Minecraft Item Wizard, CEM Template Loader, GeckoLib Animation Utils, Minecraft Block Wizard, Shape Generator, Color Gradient Generator, Animation Sliders, MTools, Cameras, Outline Creator, AzureLib Animator, Preview Scene Customiser, Plaster, Brush Color Randomizer, Bakery, Rainbow Road Game, Discord RPC, Ground Plane Editor, Activity Tracker, and Light Tracer Uploader...y'know...that's alot, probably is a plugin :sob:

**Comment by JannisX11** [comment] 2024-12-14 19:20
Duplicate of #1851

**Closed by JannisX11** 2024-12-14 19:20 UTC
