### ISSUE TITLE
Java models textures and all editor manipulation tools are invisible since 4.9.0

### ISSUE THREAD

**Issue by JosefLitos** [JannisX11/blockbench#2195] opened 2024-02-03 16:02 UTC
### What are you trying to do, and what do you expect to happen?

I'm trying to see the model I'm working with.

### What happens instead?

there's nothing, not even the base mesh. I can only see the base model without textures when switching to solid mode.

### Model format in which the issue occurs

java block

### Blockbench variant

Program

### Blockbench version

4.9.0-4.9.3

### Operating System

archlinux

view mode - textures
![obrazek](https://github.com/JannisX11/blockbench/assets/54900518/211e243a-2fe1-4db2-b461-9394a415cc96)
view mode - solid
![obrazek](https://github.com/JannisX11/blockbench/assets/54900518/1b8fc797-3a15-40fc-8aa3-c70b50725312)

notice the moving arrows don't show up in either view mode at all

### Expected
view mode - textures in 4.8.3
![obrazek](https://github.com/JannisX11/blockbench/assets/54900518/7c280b80-e5f8-4d74-8269-ce7e63a66193)

**Comment by JannisX11** [comment] 2024-02-04 17:01
Duplicate of #1964

**Closed by JannisX11** 2024-02-04 17:01 UTC
