### ISSUE TITLE
Explode Model Bug

### ISSUE THREAD

**Issue by CurrentlyCaffeinating** [JannisX11/blockbench#1413] opened 2022-05-11 17:32 UTC
When I use the explode model button when editing a player skin/mob skin, the button works normally. The problem is when I save the project without un-exploding the model, open the project, and press the explode button again. The parts can completely go apart infinitely.

**Comment by JannisX11** [comment] 2022-05-11 21:00
Duplicate of #881

**Closed by JannisX11** 2022-05-11 21:00 UTC
