### ISSUE TITLE
[Issue] BlockBench black screan web app android

### ISSUE THREAD

**Issue by valterineCraft** [JannisX11/blockbench#1548] opened 2022-09-02 02:36 UTC
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.

Please make sure to provide the following information:
- as soon as I open my block bench on my android, whether it's web app or website, and I press bedrock Entity or Java Block/item, it turns out that everything is fine, but after a few seconds of fiddling with the app, it turns out that it starts to get very lagging to the point that both the app and the website shut down all the apps on my device, but after all that the app gives the black screen bug that leaves the part where I control the object/cube totally black and that makes it completely impossible to model Even though it is possible to export and import the model, I still can't move the model I made please solve this if possible Sorry for the mistakes I'm using Google translate 
- bedrock Entity Java Block/item
- Website/app mobile
- J2 prime android 6.0.1 aarch/32Bits

**Comment by JannisX11** [comment] 2022-09-02 08:12
Duplicate of #1507

**Closed by JannisX11** 2022-09-02 08:12 UTC
