### ISSUE TITLE
Cannot Scale Meshes Uniformly Using The Resize Gizmo

### ISSUE THREAD

**Issue by simonpaulkeating** [JannisX11/blockbench#2295] opened 2024-04-25 06:36 UTC
### What are you trying to do, and what do you expect to happen?

There is no way to scale a mesh uniformly using the gizmo and the resize tool. (although it seems to work with cube primitives (add cube).)

### What happens instead?

When I drag the centre of the gizmo the mesh scales on a single axis. This seems to happen even if I hold either ctrl alt or shift too. I would expect the mesh to scale uniformly. Additionally I would expect the centre of the gizmo to highlight when I mouse over in the same way that the individual axis on the gizmo highlight.

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Window 10

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment] 2024-04-25 18:46
You are looking for the Scale tool (Transform > Scale). The resize tool is not intended for global uniform scaling.

**Comment by simonpaulkeating** [comment] 2024-04-25 20:03
Hi. I understand there are ways to do it outside of the tool, but in every other modelling program that exists, the central part of the scale gizmo scales uniformly. That is why I would class this as a design fault. There is no reason why Blockbench should have a separate command solely for uniform scaling.  Thanks

**Comment by JannisX11** [comment] 2024-04-25 20:16
Now I'm not sure if we are talking about the same thing. The center is definitely intended to resize in all directions, but for each element individually. Could you share a video of the gizmo only resizing on one axis?

**Comment by simonpaulkeating** [comment] 2024-04-25 20:54
Hi, I made a video here: [](https://app.screencast.com/cqdPVJfxG3yMB)
I am in selction mode : object when i do this as i want to scale the whole object uniformly

**Comment by JannisX11** [comment] 2024-04-25 21:06
Duplicate of #1796

**Closed by JannisX11** 2024-04-25 21:06 UTC

**Comment by simonpaulkeating** [comment] 2024-04-25 21:15
Okay then. I still don't really understand the difference, but I guess I'll just use the other tool in future then :)

Maybe there should be a 'scale' gizmo instead or in addition to the resize gizmo?
