### ISSUE TITLE
Cannot paint or erase texture

### ISSUE THREAD

**Issue by MusicScience** [JannisX11/blockbench#2268] opened 2024-04-10 04:00 UTC
### What are you trying to do, and what do you expect to happen?

"When I create a model and apply a texture, my expectation is that when I paint or erase over it, the preloaded texture will be replaced with the desired colors."

### What happens instead?

Nothing happened, as if I never painted it or erase it. Even when dealing with just a single cube, the texture remains unalterable; painting or erasing it is not an option.

https://github.com/JannisX11/blockbench/assets/81752216/b68105bf-10d1-4fdd-b6fe-93af54e8a058

### Model format in which the issue occurs

All model format, generic and bedrock model

### Blockbench variant

Website

### Blockbench version

latest version

### Operating System

Android 13

### Installed Blockbench plugins

None

**Comment by XylophoneSerpent** [comment] 2024-04-28 01:50
I am experiencing the same or similar issue just now. I was texturing a model and took a small break (closing and reopening the application) and, when I returned, I am unable to erase or paint over the existing textures, but can still paint transparent areas and erase what I have drawn in this session. I am on Windows 11 and the latest Blockbench desktop version as of posting.
Demonstration:
![Blockbench_mrP23DccA8](https://github.com/JannisX11/blockbench/assets/50330387/88a81783-c5c5-446e-b500-4ab2456167de)

**Comment by JannisX11** [comment] 2024-05-29 17:46
Duplicate of #2260

**Closed by JannisX11** 2024-05-29 17:46 UTC
