### ISSUE TITLE
Cannot paint on cubes that share the same texture when mirroring is on

### ISSUE THREAD

**Issue by pixelstoriez** [JannisX11/blockbench#1973] opened 2023-07-29 19:21 UTC
### What are you trying to do, and what do you expect to happen?

I'm trying to paint on two cubes that share the same texture, for instance two arms on a player model, but they share the same UV (to optimize space).

### What happens instead?

Whenever I have two cubes, for instance two arms on a player, but they share the same texture (to optimize UV space), I cannot paint on the sides of either of those cubes, but I can for the top, front, back, and bottom of that cube. I've recorded a video that demonstrates what happens:

https://github.com/JannisX11/blockbench/assets/68472867/f91a8aee-98da-49b4-b3b0-8e3b6750c8e5

Mirror painting on singular cubes (such as the torso in the video) works normally

### Model format in which the issue occurs

Modded entity, Bedrock entity

### Blockbench variant

Program

### Blockbench version

4.8.0

### Operating System

Windows 11

### Installed Blockbench plugins

CEM Template Loader, Simplify Models, Reference Models

**Comment by JannisX11** [comment] 2023-07-29 20:39
Duplicate of #1968

**Comment by JannisX11** [comment] 2023-07-29 20:40
Will be fixed in patch 1

**Closed by JannisX11** 2023-07-29 20:39 UTC
