### ISSUE TITLE
Issue Summary

### ISSUE THREAD

**Issue by Hulikbulik** [JannisX11/blockbench#1998] opened 2023-08-16 19:14 UTC
### What are you trying to do, and what do you expect to happen?

https://github.com/JannisX11/blockbench/assets/142442142/56fbb3a7-2a17-48f0-96d1-372027dfbe12

I fixed all the errors that were, but still nothing changes, I hope that you can help me solve this.

### What happens instead?

I have a problem. When I start painting a mob, for example, a leg, then the back is also painted, although these are two different cubes. What to do?

### Model format in which the issue occurs

model

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

homemade

**Comment by PaulFinnerty** [comment] 2023-08-16 23:39
You must have overlapping UVs, this is not a bug.

Head on over to the Discord to get help when things aren't working as you want them to: https://discord.gg/blockbench. This Github repository is meant to report bugs and suggest features. As a beginner, it's best to ask in the Discord first before making a Github Issue.

This other person was having the same issue: https://discord.com/channels/314078526104141834/1133047899085865030/1133048112831807578

If your problem ends up being different, or if you need additional help resolving it, you can make a Help post (be sure to read the rules of the Discord server to know where to ask for help)

**Closed** 2023-08-19 09:02 UTC
