### ISSUE TITLE
Nothing Shows Up Inside Blockbench

### ISSUE THREAD

**Issue by tpglitch** [JannisX11/blockbench#2310] opened 2024-05-01 22:41 UTC
### What are you trying to do, and what do you expect to happen?

I am trying to create a block in Blockbench, and i expect it to show up

### What happens instead?

even with moving camera and zoom and factory reset, nothing shows up
![image](https://github.com/JannisX11/blockbench/assets/123958345/75ab2e0a-f25f-4632-b555-aec270a73ffa)
here are the console errors:
![image](https://github.com/JannisX11/blockbench/assets/123958345/13799f78-b8b4-4eb3-b782-03049a6f616f)

### Model format in which the issue occurs

Entity Wizard Model

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Ubuntu

### Installed Blockbench plugins

Entity Wizard

**Comment by JannisX11** [comment] 2024-05-01 22:59
Duplicate of #1964

**Closed by JannisX11** 2024-05-01 22:59 UTC

**Comment by tpglitch** [comment] 2024-05-27 00:18
But I provided specifics
