### ISSUE TITLE
Scaling Non-square meshes on multiple axis doesn't keep the shape aspect ratio

### ISSUE THREAD

**Issue by Azagwen** [JannisX11/blockbench#2496] opened 2024-10-01 07:46 UTC
### What are you trying to do, and what do you expect to happen?

I am modeling using shapes such as hexagons and low poly circles, which involves scaling some of them. 

### What happens instead?

Scaling shapes such as hexagons doesn't keep the regularity/aspect ratio of them, and instead will cause them to shrink or inflate more on one axis

https://github.com/user-attachments/assets/e0b7c492-cbc8-4d5e-b0ff-104d35d453a3

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.11.1

### Operating System

Windows 10

### Installed Blockbench plugins

CEM Template Loader, Shape Generator, Cameras, MTools, Optimize, Custom Marker Colors

**Comment by Azagwen** [comment] 2024-10-01 08:07
this also happens when using the Inset tool 
![image](https://github.com/user-attachments/assets/c6ffea31-11c0-44dd-8576-cc8b9283b317)

**Comment by Azagwen** [comment] 2024-10-01 08:10
This does NOT happen in the per-face polygon UV editor, which suggest the scaling is calculated correctly there but not in the 3D viewport

**Comment by JannisX11** [comment] 2024-10-01 16:24
Duplicate of #1796

**Closed by JannisX11** 2024-10-01 16:24 UTC
