### ISSUE TITLE
[Issue] Variables break when defined more than once

### ISSUE THREAD

**Issue by MerpisMe** [JannisX11/blockbench#1710] opened 2022-12-31 22:52 UTC
### Detailed description of your issue

When variable placeholders are defined more than once (or to be more specific, "=" is placed following any variable name when it is already defined elsewhere), all instances of that variable will be broken until the extraneous definition is removed AND the session is restarted.

### Additional Info

- Here is an example of a scenario where this issue would occur:
![image](https://user-images.githubusercontent.com/27739930/210156879-cae144a7-f5dc-4599-8967-a87154957d7c.png)
Removing the additional definition from the keyframe will not fix it until the program is restarted.

- Occurs when there are definitions within two or more of the following:
   - keyframes
   - variable placeholders field
   - animation properties 

- Applies to all open projects that share the variable name in their animations.

- This can be problematic, especially with math-based animations, as accidentally typing "=" following a variable call will completely break the animation and require a restart.

### Model format in which the issue occurs

Generic, Bedrock Entity, GeckoLib Animated

### Blockbench variant

Website, PWA, Program

### Operating System

All applicable

**Comment by JannisX11** [comment] 2023-01-02 16:54
Duplicate of #1489

**Closed by JannisX11** 2023-01-02 16:54 UTC
