### ISSUE TITLE
Your computer is not compatible with WebGL

### ISSUE THREAD

**Issue by EmmarlonCoolDude** [JannisX11/blockbench#137] opened 2018-09-30 23:12 UTC
![screenshot - 10_1_2018 7_11_29 am](https://user-images.githubusercontent.com/31155166/46263977-58ecd280-c549-11e8-8fa6-b9be4b44c31d.png)
 Win 7 32 bit

**Comment by JannisX11** [comment] 2018-10-01 10:48
Duplicate of #100

**Closed** 2018-10-01 10:51 UTC
