### ISSUE TITLE
Template texture generation broken when project format is per face, but cubes are box uv.

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#2396] opened 2024-06-24 18:10 UTC
- Create a new project.
- Set the project UV mode to per face UV.
- Create a cube.
- Set the cubes UV mode to box UV.
- Create a new template texture (leave box UV unticked)
- Generated template is broken
![image](https://github.com/JannisX11/blockbench/assets/48070995/000502d8-6085-4d6c-ab81-1fc43bb60607)

**Comment by JannisX11** [comment] 2024-06-24 20:56
Duplicate of #1817

**Closed by JannisX11** 2024-06-24 20:56 UTC
