### ISSUE TITLE
Blockbench doesn't shows paint cursor(2D, 3D both) when using Wacom tablets

### ISSUE THREAD

**Issue by Madcow5** [JannisX11/blockbench#2317] opened 2024-05-08 07:44 UTC
### What are you trying to do, and what do you expect to happen?

Blockbench doesn't shows paint cursor(2D, 3D both) when using Wacom tablets
I've attached a video and would appreciate it if you could check it out.
As you can see, when you paint with the mouse, the mouse cursor is visible and the 3D and 2D brush outlines move along the mouse cursor.
However, when using a Wacom tablet, the brush outline is fixed at the initial starting point, the mouse cursor is not visible, and you can still paint.

https://github.com/JannisX11/blockbench/assets/70446667/853a7d53-5d04-4fd6-95c1-b349ff92fd14

### What happens instead?

same as above.

### Model format in which the issue occurs

All the formats

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Windows 10

**Comment by JannisX11** [comment] 2024-05-08 20:12
Duplicate of #1286

**Closed by JannisX11** 2024-05-08 20:12 UTC
