### ISSUE TITLE
Adding a pre-1.8 player model to the "Minecraft Skin" format

### ISSUE THREAD

**Issue by REMDRIFT** [JannisX11/blockbench#2229] opened 2024-03-14 03:38 UTC
### Detailed description of your suggestion

A pre-1.8 player model for the "Minecraft Skin" format. Prior to Minecraft 1.8, player models were only wide, had a resolution of 64x32, and had mirrored limbs.

It would be a rather niche feature, but I don't see why it couldn't be added for whenever someone wants to make/edit traditional skins.

**Comment by REMDRIFT** [comment] 2024-03-14 03:49
A few minutes after creating this, I realize that such a model would basically be a duplicate of the "Zombie" model.

Perhaps a pre-1.8 player model wouldn't hurt anyway, because using the zombie model isn't immediately obvious. It could basically just be the Zombie model but with the pose and template texture of the player models.

**Comment by JannisX11** [comment] 2024-03-15 21:53
Duplicate of #1546

**Closed by JannisX11** 2024-03-15 21:53 UTC
