### ISSUE TITLE
[Suggestion] Bring back ability to use arrow keys to move cubes

### ISSUE THREAD

**Issue by LordGiacomoS** [JannisX11/blockbench#168] opened 2018-10-22 15:01 UTC
Around the time of Blockbench 2.0 being released, I noticed that I could no longer use my arrow keys to move cubes. I would appreciate if this was brought back as it made my life so much easier...

**Comment by JannisX11** [comment] 2018-10-22 17:11
Duplicate of #160

**Closed by JannisX11** 2018-10-22 17:11 UTC
