### ISSUE TITLE
Android mouse click does not work properly

### ISSUE THREAD

**Issue by rick460** [JannisX11/blockbench#2178] opened 2024-01-03 23:25 UTC
### What are you trying to do, and what do you expect to happen?

I tried to use Left mouse button on vertices, edges, faces, paint. but it doesn't work correctly

### What happens instead?

 left mouse click does not work on edge, vertex or face, and it also doesn't work on paint. however it works when I use touch screen

### Model format in which the issue occurs

.

### Blockbench variant

Website, PWA

### Blockbench version

4.9.3

### Operating System

Android

**Comment by JannisX11** [comment] 2024-01-03 23:40
Duplicate of #1677

**Closed by JannisX11** 2024-01-03 23:40 UTC
