### ISSUE TITLE
[Issue] Move tool disabled

### ISSUE THREAD

**Issue by uItimatech** [JannisX11/blockbench#1206] opened 2021-12-11 19:42 UTC
-When moving elements and trying to resize them afterwards the move tool is disabled. It sometimes work again but I haven't been able to figure out the reason of this (perhaps a keybind problem, even though I already made sure there weren't 2 shortcuts binded to the same key). [see video below for more context]

-Model format: Generic
-Blockbench Program
-Unsuccessful fix attempts:
    *switching tools/tabs
    *checking keybind
    *restarting a new (generic) model
    *restarting blockbench
    *crying

(also note that I'm using the latest Blockbench version)

-Issue showcase: https://streamable.com/frf5iu

-Console:

![temp](https://user-images.githubusercontent.com/60111626/145689547-5af90bdb-ade9-4190-97e9-3b176443c8b9.PNG)

**Comment by JannisX11** [comment] 2021-12-12 00:52
Duplicate of #1201

**Closed by JannisX11** 2021-12-12 00:52 UTC
