### ISSUE TITLE
[Issue] Issue summary

### ISSUE THREAD

**Issue by BangXDty** [JannisX11/blockbench#1734] opened 2023-01-20 17:34 UTC
### Detailed description of your issue

The screen freezes when I scroll for a while but everything else works fine.

### Model format in which the issue occurs

OPPO A5s CPH1909

### Blockbench variant

Website, Program

### Operating System

Android

**Comment by JannisX11** [comment] 2023-01-20 18:28
What part of the interface exactly are you scrolling?

**Comment by BangXDty** [comment] 2023-01-21 02:38
part used to scroll through the model It freezes when I move it.

ในวันที่ ส. 21 ม.ค. 2023 01:28 น. JannisX11 ***@***.***>
เขียนว่า:

**Comment by JannisX11** [comment] 2023-04-21 17:58
Duplicate of #1729

**Closed by JannisX11** 2023-04-21 17:58 UTC
