### ISSUE TITLE
[Suggestion] A way to easily generate entity files and a blockbench that works with graphics tablets pls!

### ISSUE THREAD

**Issue by beclair** [JannisX11/blockbench#622] opened 2020-05-07 18:02 UTC
Hello, 
I used to use a plugin called "entity file generator" which would allow me to generate entity files, however, it has recently stopped working for me so I'd like to request two things:

-> Some sort of working plugin so I can easily generate entity files so I can test out my models in minecraft. (cuz im a noob and I can't figure out how to properly do this without the plugin).

-> A version of blockbench that works for graphics tablets. I work with a graphics tablet for health reasons, using a mouse really screws up my hands, so it would be amazing to have a working version I could use, I usually have to take long breaks in between model making since I cannot handle working with mouse for too long. The program does detect my tablet, but it is quite unusable at the moment: 
       -I am not able to move uv's in the uv window.
       -If I am in a non-ortographic view and try to model it snaps my camera to a weird maybe orthographic view? 
       -I am also not able to drag anything in the outliner

There are plenty of issues that happen like this, just to name a few examples.

**Comment by JannisX11** [comment] 2020-06-28 12:09
If you want a plugin that generates add-entity files, you can suggest it over at the [blockbench-plugins](https://github.com/JannisX11/blockbench-plugins) repository.

The other issue seems to be a duplicate of #623. Haven't been able to reproduce it as it works with my graphics tablet, but I will look into it more in the future.

**Closed by JannisX11** 2020-06-28 12:09 UTC
