### ISSUE TITLE
Skin not showing

### ISSUE THREAD

**Issue by zoga-com** [JannisX11/blockbench#2265] opened 2024-04-08 09:11 UTC
### What are you trying to do, and what do you expect to happen?

While editing a model of type Skin, skin is not displayed. I have tried zooming in and out the camera, tried creating an empty template and uploading my skin, but nothing works. Skin should be displayed.
![изображение](https://github.com/JannisX11/blockbench/assets/42349670/92c21b74-bbf2-416c-95d4-624a946dba1d)

### What happens instead?

Skin not showing

### Model format in which the issue occurs

Minecraft skin

### Blockbench variant

Program

### Blockbench version

4.9.4, latest flatpak

### Operating System

Fedora 39 Workstation

### Installed Blockbench plugins

Resourcepack Packager

**Comment by JannisX11** [comment] 2024-04-08 17:48
Duplicate of #1964

**Closed by JannisX11** 2024-04-08 17:48 UTC
