### ISSUE TITLE
[!] the model dissapear in edit, paint and display section ( only the GUI ) , i can still see my model in the rest slots in display section

### ISSUE THREAD

**Issue by usenamhkdrgo** [JannisX11/blockbench#943] opened 2021-06-29 08:30 UTC
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- Detailed description of your issue
- Model format in which the issue occurs 

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop)
- Operating System

**Comment by JannisX11** [comment] 2021-06-29 08:56
Please add your Blockbench version, operating system / browser, as required by the issue template.

**Comment by Ermes311** [comment] 2021-07-11 11:25
-bedrockand java model
-webapp
-3.9.2
-android
when i add a texture for my model, it goes transparent, painting on it won't do anything
but the model is still there.
it happens in bedrock and java model.

**Comment by JannisX11** [comment] 2021-07-17 18:51
Duplicate of #939

**Closed by JannisX11** 2021-07-17 18:51 UTC
