### ISSUE TITLE
[old graphics card] give supports for old graphics cards from 2010 and newer

### ISSUE THREAD

**Issue by binugamez** [JannisX11/blockbench#1752] opened 2023-02-11 04:58 UTC
### Detailed description of your suggestion

I would like that if blockbench support old graphics cards from 2010 or newer, Eg : NVIDIA GeForce 320M 256 MB
and also it needs to be done with macs because the mac between 2008 and 2016 is facing issue #1617 , i request a support for pottato pc , well windos don't have #1617 issue ,but only macs ,may be 13-inch to 15-inch MacBookPro 
Thanks devs  to making the engine amazing
from @binugamez
to @JannisX11

**Comment by JannisX11** [comment] 2023-02-11 10:10
To be clear, I am not the one who blacklists old unsupported hardware. That is done by the platform that Blockbench runs on (Electron and Chromium). I cannot just add support for individual old graphics cards.

**Comment by JannisX11** [comment] 2023-02-11 10:10
Duplicate of #593

**Closed by JannisX11** 2023-02-11 10:10 UTC
