### ISSUE TITLE
Cannot import 3D models or texture 

### ISSUE THREAD

**Issue by user34Aw** [JannisX11/blockbench#2528] opened 2024-10-23 20:46 UTC
### What are you trying to do, and what do you expect to happen?

Tried to import a texture but all my images were grey and the model too this affects Google Chrome and Microsoft Edge browsers

### What happens instead?

Can't open image and texture everything is grey

### Model format in which the issue occurs

All

### Blockbench variant

Website

### Blockbench version

4.11.1

### Operating System

Android 

### Installed Blockbench plugins

none

**Comment by JannisX11** [comment] 2024-10-23 21:39
Duplicate of #2522

**Closed by JannisX11** 2024-10-23 21:39 UTC
