### ISSUE TITLE
Display mode GUI section zoomed in and off-centre 

### ISSUE THREAD

**Issue by Arkaliasus** [JannisX11/blockbench#1935] opened 2023-07-06 10:34 UTC
### What are you trying to do, and what do you expect to happen?

Clicking the GUI option whilst in DISPLAY mode with a model open should show a graphical representation of the model inside a GUI slot for minecraft

### What happens instead?

on certain models the GUI in the display section seems to be heavily zoomed in and way off to the side of the GUIs, despite the models being the same size as other models.

The model in the screenshot provided is around 15x15x3.5
https://imgur.com/a/26GjEmC

### Model format in which the issue occurs

Java/block item

### Blockbench variant

Program

### Operating System

Windows 10 Pro

### Installed Blockbench plugins

CEM Template Loader (7.0.0), Geckolib Animation Utils (3.0.5)

**Comment by JannisX11** [comment] 2023-07-16 15:23
I cannot reproduce this. Does the UI still move and zoom with the model if you drag it around? Are there any errors in the console? (Ctrl + shift + i > Console),

**Comment by JannisX11** [comment] 2023-07-16 15:44
Duplicate of #1841

**Closed by JannisX11** 2023-07-16 15:44 UTC
