### ISSUE TITLE
Textured & Wireframe View Modes result in model becoming completely invisible

### ISSUE THREAD

**Issue by Munsterlandr** [JannisX11/blockbench#2270] opened 2024-04-14 15:13 UTC
### What are you trying to do, and what do you expect to happen?

I'm trying to look at my model with one of the stated view modes.

### What happens instead?

The model becomes completely invisible. The other view modes (Solid and UV Preview) still show the geometry fine, so my guess is that it's something to do with it not applying custom textures correctly in the case of Textured View Mode. As for wireframe, I got no idea.

Here's the errors from the console:
![Screenshot_20240414_091143](https://github.com/JannisX11/blockbench/assets/81447509/6a7e04a1-2951-4cf4-9a7f-5d0de816c906)

### Model format in which the issue occurs

bbmodel

### Blockbench variant

Program

### Blockbench version

4.9.4

### Operating System

Linux, KDE Neon 6.0.3 using X11

**Comment by Munsterlandr** [comment] 2024-04-14 15:47
checked the web app to see what would happen, turns out the issue doesn't occur on that version. Hopefully this info helps for figuring out what's being weird.

**Comment by JannisX11** [comment] 2024-04-21 16:28
Could you test if this is still an issue in the new beta? https://github.com/JannisX11/blockbench/releases/tag/v4.10.0-beta.1

**Comment by JannisX11** [comment] 2024-05-01 23:00
Duplicate of #1964

**Closed by JannisX11** 2024-05-01 23:00 UTC
