### ISSUE TITLE
[Issue] The .tbl plugin is not working

### ISSUE THREAD

**Issue by Mortauu** [JannisX11/blockbench#1155] opened 2021-11-13 11:32 UTC
Blockbench is having problems importing .tbl plugin to Modded Entity when you click to import it doesn't execute the command and nothing happens

Blockbench App

Windows 10

**Comment by JannisX11** [comment] 2021-11-13 11:55
Duplicate of https://github.com/JannisX11/blockbench-plugins/issues/189

**Closed by JannisX11** 2021-11-13 11:55 UTC
