### ISSUE TITLE
[Issue] Issue summary

### ISSUE THREAD

**Issue by withersoul1** [JannisX11/blockbench#997] opened 2021-08-20 16:44 UTC
![צילום מסך 2021-08-20 192216](https://user-images.githubusercontent.com/89269037/130265879-ceb04394-5032-4ddb-9bd2-b1789cee4d06.png)
 when I open blockbench I get this message I removed and installed it again and again and yes I downloaded the latest version of blockbench currently using the web app but I don't know if only I have this issue.

**Comment by JannisX11** [comment] 2021-08-21 08:50
Duplicate of #964, you can find instructions on how to temporarily solve the issue in that thread.

**Closed by JannisX11** 2021-08-21 08:50 UTC
