### ISSUE TITLE
[Issue] Item list problem

### ISSUE THREAD

**Issue by zxhfh** [JannisX11/blockbench#755] opened 2020-11-01 04:40 UTC
For issues, please provide the following informations:
- Detailed description of your issue
When there are too many components or blocks, I cannot scroll down the list.  It will think of "move this component"
![Screenshot_20201101_122557](https://user-images.githubusercontent.com/64130742/97795251-f3df9b80-1c3e-11eb-8f56-d2945b4e0d1b.jpg)

- Model format in which the issue occurs 
**All**

**Comment by JannisX11** [comment] 2021-02-21 11:00
Duplicate of #782

**Closed by JannisX11** 2021-02-21 11:00 UTC
