### ISSUE TITLE
Model not loading in viewport

### ISSUE THREAD

**Issue by Stick404** [JannisX11/blockbench#2161] opened 2023-12-27 04:18 UTC
### What are you trying to do, and what do you expect to happen?

When ever I click on a model to edit it, instead it shows a blank viewport. Stranger is I can still click on the model, just I can't see it
![what the viewport is](https://github.com/JannisX11/blockbench/assets/93604201/6a8e3f9e-6d2b-49d3-bdb0-9746283e507b)

### What happens instead?

the viewport is empty, and only the background is shown, not even the little ground used for 0,0,0 can be seen. (error stuffs and console found
![here,](https://github.com/JannisX11/blockbench/assets/93604201/6212fe2d-b2bb-41d7-b7c0-19174dba2a40) 
![and here](https://github.com/JannisX11/blockbench/assets/93604201/6f85525f-59f4-44b2-a130-7b37ec201052)

### Model format in which the issue occurs

standard moddel format

### Blockbench variant

Program

### Blockbench version

4.9.2

### Operating System

Linux Mint 21.2 Cinnamon

### Installed Blockbench plugins

Figura model type (unused as far as I know)

**Comment by candyCalc** [comment] 2023-12-29 06:38
It seems to be a problem specifically with the linux version. I tested this with the web, windows in a vm, and linux version and the latter was the only one that didn't work.
![Screenshot from 2023-12-28 22-34-00](https://github.com/JannisX11/blockbench/assets/109626643/a14ae0ab-37c8-40c6-8407-52aa6b95e65d)
![Screenshot from 2023-12-28 22-28-00](https://github.com/JannisX11/blockbench/assets/109626643/aed28c88-09a5-4f6a-b012-fde3914ed5fc)
![Screenshot from 2023-12-28 22-26-17](https://github.com/JannisX11/blockbench/assets/109626643/b4e28620-620a-42b8-90bd-ef7eabbdbd45)
and perhaps the issue is even more specific, because I happen to also be running the exact same linux mint version as Stick404 is.

**Comment by JannisX11** [comment] 2024-01-01 13:13
Duplicate of #1964

**Closed by JannisX11** 2024-01-01 13:13 UTC
