### ISSUE TITLE
[Suggestion] Mob skins that use different textures should use multiple textures instead of one

### ISSUE THREAD

**Issue by Pythagoras-314** [JannisX11/blockbench#850] opened 2021-03-08 23:32 UTC
It's fairly simple: Mobs that use two different textures should use two different textures when creating a mob skin. This makes it easier to replace a texture. Take the sheep, for example. It has 2 textures used for it: sheep.png and sheep_fur.png. When trying to replace the one Blockbench preview with my own texture, it's quite annoying. If it used two different templates, it would be a lot easier to replace the textures, and you could hide one texture and keep the other visible. This could also be helpful in the case of mobs like the Drowned, which doesn't have a template as you're supposed to use the Steve or Husk model instead.

**Comment by dragonmaster95** [comment] 2021-03-09 17:22
For which format would you suggest this idea? (and don't say "all" please)

**Comment by Pythagoras-314** [comment] 2021-03-09 23:29
What do you mean by format?

**Comment by JannisX11** [comment] 2021-11-09 21:08
Duplicate of #741

**Closed by JannisX11** 2021-11-09 21:08 UTC
