### ISSUE TITLE
[Issue] Low Poly models not see

### ISSUE THREAD

**Issue by Gelufis** [JannisX11/blockbench#1715] opened 2023-01-04 11:44 UTC
### Detailed description of your issue

i cant see strings and the block i cant animate on mac 
![Bildschirmfoto 2023-01-04 um 12 44 02](https://user-images.githubusercontent.com/116276815/210548048-7fbe1bf2-5ead-49cc-92e4-e79b3938b9a9.png)

### Model format in which the issue occurs

all

### Blockbench variant

Program

### Operating System

macOS Catalina 10.15.7

**Comment by JannisX11** [comment] 2023-01-07 12:42
Duplicate of #1617

**Closed by JannisX11** 2023-01-07 12:42 UTC

**Comment by binugamez** [comment] 2023-01-14 05:18
Same for all macOs
I am so angry that you dev did good job yesterday fixing it but it came back again,
it not our graphics probleme its the support for macOs , you have time untill next week, if not fixed we macOs users will never use this software again
