### ISSUE TITLE
Invisible icons

### ISSUE THREAD

**Issue by KTHOMRN** [JannisX11/blockbench#1439] opened 2022-06-01 18:12 UTC
![IMG_20220602_020954](https://user-images.githubusercontent.com/106698353/171473757-89064d48-2291-4686-9436-575e3d98e857.png)
![Uploading IMG_20220602_021003.png…]()

It has errors in version 4.2.4
windows 10

**Comment by JannisX11** [comment] 2022-06-02 17:47
Duplicate of #1371

**Closed by JannisX11** 2022-06-02 17:47 UTC
