### ISSUE TITLE
Model is invisible

### ISSUE THREAD

**Issue by YTFrost** [JannisX11/blockbench#2001] opened 2023-08-18 10:09 UTC
### What are you trying to do, and what do you expect to happen?

When I open up Blockbench, I expect the cubes I add to be visible in the preview window.

### What happens instead?

None of the cubes are visible, in none of the tabs.
https://github.com/JannisX11/blockbench/assets/55927438/15016ca2-30f8-49e5-8894-89b4ca1e50d7

### Model format in which the issue occurs

All of them

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

EndeavourOS

### Installed Blockbench plugins

Minecraft Title Generator
CEM Template Loader
GeckoLib Animation Utils
Shape Generator
Plaster
Optimize
Activity Tracker

**Comment by JannisX11** [comment] 2023-08-19 09:04
How did you install the program?

**Comment by YTFrost** [comment] 2023-08-19 09:42
I installed it through the Arch User Reposirory. It worked fine for a few months, bur stopped recently. My guess would be an update broke it

**Comment by YTFrost** [comment] 2023-08-19 15:41
Update, appImage from github also has the same issue

**Comment by JannisX11** [comment] 2023-08-19 18:22
Duplicate of #1964

**Closed by JannisX11** 2023-08-19 18:22 UTC
