### ISSUE TITLE
[Suggestion] Relative texture size Auto UV

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#357] opened 2019-06-25 18:47 UTC
[JAVA MINECRAFT] Relative texture size Auto UV (Not quite sure what to call this) 
This would be useful for creating texture templates/atlases manually on large textures.

First you would have to define texture size (Which is on project and has no use really right now, also it really just needs one value because all textures are square)

Heres some examples (Auto UV on a 16x16x16 cube face) (with normal auto UV this would just do a 16x16 scale UV)
![image](https://user-images.githubusercontent.com/44243757/60124010-61e59a00-9791-11e9-8f81-e40ebe698fd9.png)

**Comment by JannisX11** [comment] 2019-07-02 10:37
Duplicate of #128

**Closed by JannisX11** 2019-07-02 10:37 UTC
