### ISSUE TITLE
Local Rotation doesn't work when animating

### ISSUE THREAD

**Issue by CanineGray** [JannisX11/blockbench#1978] opened 2023-07-31 03:20 UTC
### What are you trying to do, and what do you expect to happen?

When setting the rotation space to Local it rotates as expected in edit mode 
![squid - Converted](https://github.com/JannisX11/blockbench/assets/95171931/c881f583-778e-4f20-87e1-bcb29667e619)

### What happens instead?

When animating it ignores local rotation and does not change the rotation of each axis
![squid - Converted2](https://github.com/JannisX11/blockbench/assets/95171931/5bd415ac-50d6-491d-9b05-b7f5081d3465)

### Model format in which the issue occurs

Generic model

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

Windows

### Installed Blockbench plugins

CEM temp. loader

**Comment by Eliaskandil** [comment] 2023-11-29 15:40
same omg

**Comment by hawwwwwk** [comment] 2023-12-17 21:49
same,,, is there a fix for this yet??

**Comment by JannisX11** [comment] 2024-04-21 21:54
This works as intended. Transform spaces only change how the transform tool (rotation tool) works, not how the numbers behave.

**Closed by JannisX11** 2024-04-21 21:54 UTC
