### ISSUE TITLE
[Issue] There's no icon for blockbench (the name's there) in cinnamenu on Linux Mint 20.3 cinnamon

### ISSUE THREAD

**Issue by Nathan22211** [JannisX11/blockbench#1279] opened 2022-02-08 11:48 UTC
- Before you report an issue, check if if has already been reported.
- Also check if you are using the latest version of Blockbench.
- If applicable, go to Help > Developer > Open Dev Tools. Switch to the Console tab. If there are any (red) error messages, please attach a screenshot of them.
(Doesn't pertain to the functionality of the app itself)

Please make sure to provide the following information:
- Detailed description of your issue
- Model format in which the issue occurs
- Blockbench variant (Website / PWA / Program)
- Operating System

there's no icon on the program when installed on linux mint 20.3 cinnamon via the deb package
(doesn't pertain to this)
program
Linux mint 20.3 Cinnamon (might happen with other ubuntu
![blockbench bug](https://user-images.githubusercontent.com/35241068/152981484-51e60db2-3c91-480e-86b6-5086d0b8f63b.png)
![cinnamenu](https://user-images.githubusercontent.com/35241068/152981491-00ea6d0a-4bda-4788-a185-23670ef991fb.png)
 distros that use the same desktop)

**Comment by Nathan22211** [comment] 2022-02-08 11:51
sorry for the weird split in the text I have no idea why GitHub did that

**Comment by JannisX11** [comment] 2022-05-22 10:17
Duplicate of #1207

**Closed by JannisX11** 2022-05-22 10:17 UTC
