### ISSUE TITLE
Pivot Move Axes Don't Match Rotation

### ISSUE THREAD

**Issue by GronyRalph** [JannisX11/blockbench#1923] opened 2023-06-24 21:49 UTC
### What are you trying to do, and what do you expect to happen?

Let's say you create a plane and rotate it, the moment you're gonna move, scale, etc... that rotated plane, the axes of those tools will match its rotation making it easier for example to duplicate it by its side, that's a feature
![image](https://github.com/JannisX11/blockbench/assets/56495047/e5f5e976-eda4-489b-85ae-aa8349653461)
So I'm expecting Pivot points to do the same to make it easier to move them within the object they belong to

### What happens instead?

Pivot points tool axes don't match the rotation making it way harder to work with them in these cases, they stay straight
![image](https://github.com/JannisX11/blockbench/assets/56495047/214d7d17-ac2d-4b8a-b240-bfe2384f60fe)

### Model format in which the issue occurs

Generic Format

### Blockbench variant

Program

### Operating System

Windows 10

### Installed Blockbench plugins

None

**Comment by JannisX11** [comment] 2023-06-25 00:15
Duplicate of #774

**Closed by JannisX11** 2023-06-25 00:15 UTC
