### ISSUE TITLE
Give the option to enable repeating textures

### ISSUE THREAD

**Issue by caioraphael1** [JannisX11/blockbench#2422] opened 2024-07-13 22:23 UTC
In this image I have a 16x16 texture, placed in a 16x16 block. 

![image](https://github.com/user-attachments/assets/4f6ac829-f91f-42e0-a6cc-efc495fa1d27)

I'd like that each face of the block had the texture applied to it. That's achievable by giving the option to enable Texture Repeat in the texture options. 

This option could be placed here:
![image](https://github.com/user-attachments/assets/5870a7eb-9de1-4cbb-b0a2-8980a804e794)

That's all that's needed to solve the issue.

I can, for example, export this cube as a GLB and edit its material inside Godot, enabling Texture Repeat and making the texture show as expected. 

I wish this was possible inside Blockbench.

This feature makes a lot of sense for game development in general, as its cheaper to load a small texture, but this would also create the possibility of creating a workflow involving "tilemaps".
- For example: resizing a cube would make the texture repeat itself, which can be great for prototyping or creating whole maps. The alternative used is to keep duplicating the current cube, which is really boring to do.

I really hope this gets added! 
Thanks :)

**Comment by JannisX11** [comment] 2024-07-14 09:34
Duplicate of #1391

**Closed by JannisX11** 2024-07-14 09:34 UTC
