### ISSUE TITLE
Animation record

### ISSUE THREAD

**Issue by foxitor** [JannisX11/blockbench#2562] opened 2024-11-17 16:43 UTC
### Detailed description of your suggestion

when i need to record an animation i have no choice but to record a gif, i want to be able to save it in mp4 format.

**Comment by JannisX11** [comment] 2024-11-17 22:04
https://www.blockbench.net/plugins/scene_recorder

**Comment by JannisX11** [comment] 2024-11-21 23:42
Duplicate of #1521

**Closed by JannisX11** 2024-11-21 23:42 UTC

**Comment by foxitor** [comment] 2024-12-10 20:10
> https://www.blockbench.net/plugins/scene_recorder

thx!
