### ISSUE TITLE
[Issue]      Dont work "Local Position"

### ISSUE THREAD

**Issue by YOHEMAL** [JannisX11/blockbench#759] opened 2020-11-06 03:27 UTC
BlockBench at Desktop , OS: Windows10 64bit

Pls look a video. It doesnt work positioning at local.Please fix it , ASAP.....TT
[PLSWATCH.zip](https://github.com/JannisX11/blockbench/files/5498819/PLSWATCH.zip)

**Comment by JannisX11** [comment] 2020-11-07 17:52
Duplicate of #757

**Closed by JannisX11** 2020-11-07 17:52 UTC
