### ISSUE TITLE
[Suggestion] Tooltips dynamic selection

### ISSUE THREAD

**Issue by teuszoio** [JannisX11/blockbench#184] opened 2018-11-14 22:26 UTC
the selection mode needs an upgrade. the dynamic selection used in photoshop can also be applied.

**Comment by teuszoio** [comment] 2018-11-14 22:30
maybe using shift + something

**Comment by JannisX11** [comment] 2018-11-15 15:12
What exactly is the suggestion here? Is this a duplicate of https://github.com/JannisX11/blockbench/issues/180 ?

**Comment by teuszoio** [comment] 2018-11-15 17:15
I had not read this other topic until I sent mine. but it's the same thing

**Comment by JannisX11** [comment] 2018-11-15 18:07
Duplicate of #180

**Closed by JannisX11** 2018-11-15 18:07 UTC
