### ISSUE TITLE
[Suggestion] Ability to Toggle face edges affecting texture painting in paint mode

### ISSUE THREAD

**Issue by TheEmbracedOne** [JannisX11/blockbench#1868] opened 2023-05-05 17:03 UTC
## Problem
Edges seem to affect the painting. See in this gif what I mean:
![Blockbench_QGDV9UTy1B](https://user-images.githubusercontent.com/16197906/236520434-99a3546e-5b21-4299-a057-ce4bfa8e9e03.gif)

### Proposed Solution:
I'd love for there to be an option that'd make it so edges don't affect the painting. I think it's a super useful feature for when you dont want your paint to go out of the face beyond the edge, but perhaps this should be a toggle-able feature?

**Comment by JannisX11** [comment] 2023-05-05 17:23
Please only put one suggestion into a suggestion.
Your second issue would be solved by a screen-space projected brush (#1384), that's the only way really. If the edges are connected on the texture it will already paint beyond edges.

**Comment by TheEmbracedOne** [comment] 2023-05-05 17:29
Thank you @JannisX11 for quick response! I split my suggestions into two (other one here: #1869 
Thank you for the suggestion, is the screen-space projected brush as mentioned in #1384 available in version 4.6.5? If not, which version has this functionality?

**Comment by JannisX11** [comment] 2023-05-05 18:06
It's currently only a suggestion.

**Comment by JannisX11** [comment] 2023-05-05 18:06
Duplicate of #1384

**Closed by JannisX11** 2023-05-05 18:06 UTC
