### ISSUE TITLE
Mirror painting is broken.

### ISSUE THREAD

**Issue by Nediamail05** [JannisX11/blockbench#1975] opened 2023-07-30 04:40 UTC
### What are you trying to do, and what do you expect to happen?

I turn on mirror painting expecting it to work like normal.

### What happens instead?

Instead, I can't paint at all, not on either side of the mirror.
Happens with both X and Z axis mirrors.

### Model format in which the issue occurs

Generic model, box UV

### Blockbench variant

Program

### Blockbench version

4.8.0

### Operating System

Windows 11

### Installed Blockbench plugins

Entity Wizard, Block Wizard, Geckolib Animation Utils, Minecraft Title Generator, Animation Sliders, and Plaster.

**Comment by JannisX11** [comment] 2023-07-30 09:37
Duplicate of #1968
Fixed in 4.8.1.

**Closed by JannisX11** 2023-07-30 09:37 UTC
