### ISSUE TITLE
[Issue] Creating a new texture from a mesh doesn't preserve any currently applied textures

### ISSUE THREAD

**Issue by pedestriantactics** [JannisX11/blockbench#1259] opened 2022-01-19 19:30 UTC
A feature I'm relying heavily on is selecting multiple objects that I may have painted individually and then creating a new texture from all of them. This nicely arranges them all on the same UV map and pulls any current texture applied to them and atlases it to a megatexture. This only seems to work with cubes though. Any meshes in the mix don't have any current texture preserved when migrating to a new texture. 

This issue can easily be recreated by creating a mesh with a texture, painting some detail on the mesh, and then creating a new texture from the selected mesh. Nothing is preserved.

**If anyone has a current workaround for this I would love to hear it.** I'm working on a large interior and unwrapped most of the elements to one texture. I have since added more elements and want to combine them all in, but if I combine them, I lose everything that was painted on to the meshes within my model.

MacOS 12.1
Blockbench 4.1.3

**Comment by JannisX11** [comment] 2022-01-21 11:17
Duplicate of #1066

**Closed by JannisX11** 2022-01-21 11:17 UTC
