### ISSUE TITLE
Mirror modeling on Meshes

### ISSUE THREAD

**Issue by Mad969** [JannisX11/blockbench#2120] opened 2023-12-02 08:27 UTC
### What are you trying to do, and what do you expect to happen?

I am working on a human model on the waist I put on Mirror modeling to make the work go faster Someone was helping me,

### What happens instead?

It duped something we don't know what it increased the file size up to 10MB everything is thing until I click that on mesh 
![image](https://github.com/JannisX11/blockbench/assets/152685981/69f1f904-59d5-4148-8c00-3de670fe1be8)

### Model format in which the issue occurs

Generic Format

### Blockbench variant

Program

### Blockbench version

Blockbench 4.8.3 Desktop 

### Operating System

Windows

**Comment by Mad969** [comment] 2023-12-02 08:31
![image](https://github.com/JannisX11/blockbench/assets/152685981/4978d14e-b55a-40e9-a064-065717dd0e14)
I also found this

**Comment by JannisX11** [comment] 2023-12-02 12:59
Duplicate of https://github.com/JannisX11/blockbench/issues/2081

**Comment by JannisX11** [comment] 2023-12-02 13:00
Should be fixed in 4.9.

**Closed by JannisX11** 2023-12-02 12:59 UTC
