### ISSUE TITLE
[Suggestion] Suggestion summary

### ISSUE THREAD

**Issue by ying4937** [JannisX11/blockbench#989] opened 2021-08-11 06:18 UTC
I want to add a modeling vertex to blockbench modeling, which overlaps with each other

Connect the corners of one model to the corners of another model

**Comment by ying4937** [comment] 2021-08-11 06:31
If you can, you also want to add a vertex rotation or trim movement

**Comment by ying4937** [comment] 2021-08-13 01:46
oh Sorry, I didn't see this feature, but I still want to add vertex rotation and translation

**Comment by JannisX11** [comment] 2021-11-17 18:42
Could you describe your suggestion in more detail?

**Comment by JannisX11** [comment] 2023-02-22 18:39
Duplicate of #665

**Closed by JannisX11** 2023-02-22 18:39 UTC
