### ISSUE TITLE
Cannot color pick from reference images in image editor

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#2082] opened 2023-11-09 16:07 UTC
### What are you trying to do, and what do you expect to happen?

Color pick from a reference image in the image editor.

### What happens instead?

My click ignores the reference image, it only color picks from the loaded texture.

### Model format in which the issue occurs

Image Editor

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

W10

### Installed Blockbench plugins

N/A

**Comment by JannisX11** [comment] 2023-11-09 20:57
Duplicate of #1902

**Closed by JannisX11** 2023-11-09 20:57 UTC
