### ISSUE TITLE
[Issue] Even if the sidebars are swapped, all tooltips still appear on the right side

### ISSUE THREAD

**Issue by GitWither** [JannisX11/blockbench#60] opened 2017-08-05 19:26 UTC
Part of this issue was fixed with #57 but the tooltips and other stuff still appears there.

**Comment by JannisX11** [comment] 2017-08-11 19:04
Can't reproduce. Please send a screenshot.

**Comment by GitWither** [comment] 2017-08-12 11:40
![image](https://user-images.githubusercontent.com/29360565/29240355-b7b3259e-7f63-11e7-9efc-45e09d48b0ad.png)
![image](https://user-images.githubusercontent.com/29360565/29240359-cc2f4e44-7f63-11e7-8152-65495b560085.png)

**Comment by JannisX11** [comment] 2017-08-12 13:23
Fixed in 1.9

**Closed** 2017-08-28 20:10 UTC
