### ISSUE TITLE
[Suggestion] Skinned/Rigged mesh animation support

### ISSUE THREAD

**Issue by jhm-ciberman** [JannisX11/blockbench#1866] opened 2023-05-04 03:01 UTC
## Scenario

I'm currently developing a game with low poly pixel art textures. I started using Blender for the assets but I'm switching to Blockbench since It's a lot more straightforward to use for my specific art style. 

The game I'm working on It's a sims-like game. There are furniture objects and the player can interact with those objects. So I need to design the player animations along with the object I'm designing.

My current plan is to move my workflow from blender to Blockbench for the objects, and edit the character outfits in blender since they require rigging and animation. 

![image](https://user-images.githubusercontent.com/7988351/236101455-ffb52027-2b64-42db-aef0-1326ae2f5126.png)

## Feature request

My main concern is that it would be nice to be able to animate my characters in blockbench since animation in Blockbench feels a lot easier than in blender. 
I don't want to necesarily rig the model inside Blockbench (althought that would be nice), but just import a rigged model in GLTF (See https://github.com/JannisX11/blockbench/issues/1814) and be able to animate it using the existing animation tools inside Blockbench.

**Comment by JannisX11** [comment] 2023-05-06 20:45
Duplicate of #1679

**Closed by JannisX11** 2023-05-06 20:45 UTC
