### ISSUE TITLE
[Issue] No picture for models made by person on mac

### ISSUE THREAD

**Issue by Flamemanmacuser** [JannisX11/blockbench#1616] opened 2022-10-23 23:20 UTC
i use mac and i can't see the model when i make it, it won't work i change all my settings and couldn't see it still any questions message me at victoriabanjak@gmail.com

**Comment by JannisX11** [comment] 2022-11-03 21:01
Duplicate of #1617

**Closed by JannisX11** 2022-11-03 21:01 UTC
