### ISSUE TITLE
I can't import files

### ISSUE THREAD

**Issue by Clydehendrick** [JannisX11/blockbench#2524] opened 2024-10-22 14:00 UTC
### What are you trying to do, and what do you expect to happen?

I was trying to import a .json file, because i want to add more details to the model

### What happens instead?

It didn't let me import any file except images it is all locked

### Model format in which the issue occurs

Anything that has "." like .json, .geo, etc...

### Blockbench variant

Website, PWA

### Blockbench version

Latest

### Operating System

Android

### Installed Blockbench plugins

Nothing

**Comment by PolarFreddy** [comment] 2024-10-22 16:46
I'm having the same problem but I can't import anything like textures .bbmodel .json anything

**Comment by S0nicCr8ft** [comment] 2024-10-22 17:54
> I'm having the same problem but I can't import anything like textures .bbmodel .json anything

They banned importing files on Android

**Comment by PolarFreddy** [comment] 2024-10-22 20:00
Oh ok is the ban permanent or was it by mistake something like that or was it intentional

**Comment by JannisX11** [comment] 2024-10-22 20:39
Duplicate of #2522

**Closed by JannisX11** 2024-10-22 20:39 UTC
