### ISSUE TITLE
[issues] Pivot Tool and Rotate Tool don't align with the Local Space

### ISSUE THREAD

**Issue by Luizilipe** [JannisX11/blockbench#798] opened 2021-01-05 22:53 UTC
In Edit mode, you go into Pivot Tool and have selected Local in Transform Space, the arrows do not align with Local Space, they remain aligned with Global Space.
[Pivot Tool bug video](https://youtu.be/19dDKnkvgnY)

 In Edit mode, you go into Rotate tool and have selected Local in Rotate Space, the rotation of the y and z axes do not correspond with the Local Rotation Space.
[Rotate Tool bug video](https://youtu.be/naMgLISSas4) 

_(I tested Blockbench in the app for windows and in the Webapp on two different devices)_

**Comment by JannisX11** [comment] 2021-01-10 13:25
Duplicate of #774

(Regarding the rotation gizmo, this is due to how rotations work (look up "gimbal lock"). So this behavior is intended.)

**Closed by JannisX11** 2021-01-10 13:25 UTC
