### ISSUE TITLE
I reported a bug about faces bugging out. It was closed due to supposedly being solved and and a mod responded with a bunch of code i didn't understand. I asked if an update patched an issue and they didn't respond.

### ISSUE THREAD

**Issue by cyanbug01** [JannisX11/blockbench#2146] opened 2023-12-09 20:42 UTC
### What are you trying to do, and what do you expect to happen?

When I make a new texture, the faces in the other textures bug out. Moderator responded with a bunch of code, but I didn't understand if it was an update with a bug patch or if I had to fix it. Bug was not patched when I opened blockbench afterwards

### What happens instead?

Faces glitch out

### Model format in which the issue occurs

Basic

### Blockbench variant

Program

### Blockbench version

Most recent 

### Operating System

Windows 11

**Comment by JannisX11** [comment] 2023-12-09 20:50
Duplicate of #2133

**Closed by JannisX11** 2023-12-09 20:50 UTC
