### ISSUE TITLE
[Issue] Not Allowing me to see my model in Apple Mac

### ISSUE THREAD

**Issue by Din0boy1** [JannisX11/blockbench#975] opened 2021-07-27 20:55 UTC
When I was trying to model a thorn block, I noctice that I can't see the base or my model at all, I don't know why does this happen, but it is in the BB Program, the model was a small cube at the time of reporting.

**Comment by JannisX11** [comment] 2021-07-28 15:50
Please provide more details and screenshots of your issue.

**Comment by JannisX11** [comment] 2023-01-07 12:49
Duplicate of #1617

**Closed by JannisX11** 2023-01-07 12:49 UTC
