### ISSUE TITLE
[can't see anything in workspace in mac] when I open blockbench I can't see anything in my workspace in my mac 

### ISSUE THREAD

**Issue by binugamez** [JannisX11/blockbench#1719] opened 2023-01-07 08:27 UTC
### Detailed description of your issue

Idk why , My macbookpro and my iMac has same issue, my macbook is mid 2010 and iMac late 2009, my macbooks graphics card is NVIDIA GeForce 320M 256 MB, but not seeing any thing in my workspace but no issue with blender, I reported this thing one time but no respond , If it is the issue of the device compatibility then it make no since giving support macbook running  macOs high seirra and older, but pls fix it i begging you devs

### Model format in which the issue occurs

blank in workspace for mac

### Blockbench variant

Program

### Operating System

macOS high seirra

**Comment by JannisX11** [comment] 2023-01-07 12:39
Duplicate of #1617

**Closed by JannisX11** 2023-01-07 12:39 UTC
