### ISSUE TITLE
Constraints Feature in Blockbench

### ISSUE THREAD

**Issue by Flizer62** [JannisX11/blockbench#2315] opened 2024-05-05 10:57 UTC
https://github.com/JannisX11/blockbench/assets/137359170/4995cd93-458c-44d3-9d2f-f6d89d261799

### Detailed description of your suggestion

Incorporate constraints functionality into Blockbench to facilitate smoother character animation, particularly in leg movement. Constraints would streamline the animation process, providing users with more intuitive tools for controlling joints and ensuring realistic motion, especially when dealing with longer animations or complex movements like walking or running.

Despite the presence of null objects, they do not effectively aid in proper leg and foot movement due to their limited capabilities.

Introducing constraints to Blockbench would significantly elevate its utility for character animators, enabling them to produce professional-grade animations with greater ease and efficiency.

**Comment by JannisX11** [comment] 2024-05-05 20:01
This is in practice the same as #1775 right?

**Comment by Flizer62** [comment] 2024-05-06 00:17
> This is in practice the same as #1775 right?

Yeah

**Comment by JannisX11** [comment] 2024-05-06 18:42
Duplicate of #1775

**Closed by JannisX11** 2024-05-06 18:42 UTC
