### ISSUE TITLE
[Issue] Cannot enter negative values to display settings

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#279] opened 2019-03-19 18:17 UTC
Cannot enter negative values to display settings.
Also negative symbol disappears after removing numbers

![issue](https://user-images.githubusercontent.com/44243757/54631059-de2a5c00-4a83-11e9-8ae8-afec068adef0.gif)

Blockbench 2.5.1

**Comment by JannisX11** [comment] 2019-03-19 21:26
Duplicate of #214

**Closed by JannisX11** 2019-03-19 21:26 UTC
