### ISSUE TITLE
[Issue] Inability to import structures

### ISSUE THREAD

**Issue by CrispyMiner** [JannisX11/blockbench#587] opened 2020-04-17 21:57 UTC
Whenever I tried to import a structure, every time it errored saying that a blockstate file wasn't found despite being the blockstate was a part of the resource pack I'm trying to get the assets from. This is probably something to due with "minecraft:" being before every mentioning of a block in the code but I'm not sure.

**Comment by JannisX11** [comment] 2020-04-18 13:52
This would be an issue with the structure imporer plugin.
Most likely a duplicate of https://github.com/JannisX11/blockbench-plugins/issues/33

**Closed** 2020-04-18 13:52 UTC
