### ISSUE TITLE
Crash when closing all tabs

### ISSUE THREAD

**Issue by eschan145** [JannisX11/blockbench#1949] opened 2023-07-09 23:13 UTC
### What are you trying to do, and what do you expect to happen?

I was closing down Blockbench and closed down all tabs. After I closed all projects there was a tab called "New Tab". I expected Blockbench to close properly without displaying an error message.

### What happens instead?

When I closed the tab "New Tab" Blockbench exited and showed an error:

![image](https://github.com/JannisX11/blockbench/assets/103769713/06e6867c-8fb1-453d-ada1-4b8a16b9156b)

Probably because Blockbench didn't handle closing the application correctly. However pressing the ❌ at the top of the screen works normally.

### Model format in which the issue occurs

Not applicable

### Blockbench variant

Program

### Operating System

Windows 10 (probably not important)

### Installed Blockbench plugins

Not applicable

**Comment by JannisX11** [comment] 2023-07-10 16:58
Duplicate of #1889
Will be fixed in the next version.

**Closed by JannisX11** 2023-07-10 16:58 UTC
