### ISSUE TITLE
[Issue] Blockbench Plugins installation not working

### ISSUE THREAD

**Issue by Type-32** [JannisX11/blockbench#972] opened 2021-07-20 11:59 UTC
So when I click the "install" button of the Plugins menu the plugin won't download automatically. I assume that it has something to do with my connection, but I've checked the firewalls and my router and they're completely fine. I tried different internets and restarting the Blockbench program but it still didn't work. Here is the screenshot of the Blockbench Console below:
![image](https://user-images.githubusercontent.com/87076491/126319611-30d8961f-03f4-49d3-967e-3bb54fb571f9.png)

-------Computer Info-------
Blockbench Version: 3.9.2
Blockbench variant: Program
Operating System: Windows 11 Insider Preview

Tried methods but didn't work: Restarting computer, restarting blockbench, restarting internet, restarting router, switching internet, checking router and internet connection

**Comment by JannisX11** [comment] 2021-07-20 21:38
Duplicate of #969

**Closed** 2021-07-21 10:17 UTC
