### ISSUE TITLE
[Issue] Models not loading correctly 

### ISSUE THREAD

**Issue by kayracam** [JannisX11/blockbench#885] opened 2021-04-22 20:12 UTC
When I try export my model, and then load it to the game it doesn't load properly. Its supposed to look like this,
![image](https://user-images.githubusercontent.com/73849837/115778874-c9c59580-a3a6-11eb-8bdb-c68c2ce6b5c7.png) But instead it looks like this in-game, 
![image](https://user-images.githubusercontent.com/73849837/115779045-fe395180-a3a6-11eb-9272-c8ec6437cb77.png)
 and I've tried fixing it but nothing works.

**Comment by MC874** [comment] 2021-05-09 14:30
# Introduction
I have also this bug back then.. the problem was, you have cubes with decimal value with more 3 digits or small cubes size. Some people recommend to scale the model or fix the cubes decimal relative to 1-3 digits. Oh yeah, its also ONLY affect on player (Custom 3D Skins or resource-pack)

# Problematic
Actually i dont really know what the problem is, but  those recommendation doesnt really help. Switching to both different 1.10 and 1.12 format, the bug still occured. I end up using Polymesh model to support decimal size or uv padding. Weird enough, when i try to replace it with zombie geometry (other than player), the model is goodly defined without cube-loses or even z-fighting.

# In-game Screenshot
![image](https://user-images.githubusercontent.com/62210133/117575800-96586a00-b10d-11eb-9735-6195f37dba9c.png)

**Comment by JannisX11** [comment] 2021-06-29 07:55
You can also switch to Face-UV in the project settings to avoid this issue. This is intended behavior in Minecraft bedrock though and not an issue on Blockbench's side, so I will close this issue.

**Closed by JannisX11** 2021-06-29 07:55 UTC
