### ISSUE TITLE
[Issue] Edges textures are weird

### ISSUE THREAD

**Issue by theDevIsALie** [JannisX11/blockbench#360] opened 2019-07-08 19:23 UTC
I'm using Windows 10 and i use the Desktop variant of Blockbench.
![image](https://user-images.githubusercontent.com/50375282/60836520-25209680-a1c6-11e9-95c8-1f6623671bcf.png)
I used auto UV and i tried to fix the problem with Plaster, but it didn't fix the problem.
I think the problem is from the UV, but i'm not sure.
It's not supposed to be green on the edges.

**Comment by iWackyMinecraft** [comment] 2019-07-08 19:31
I would also recommend sending the model here @theDevIsALie

**Comment by theDevIsALie** [comment] 2019-07-08 19:41
[male_humanbody_example_eliott.zip](https://github.com/JannisX11/blockbench/files/3369976/male_humanbody_example_eliott.zip)
This is the model with the associated texture.

**Comment by theDevIsALie** [comment] 2019-07-09 09:45
Also, it does this on every edges of the model.

**Comment by JannisX11** [comment] 2019-07-09 10:20
The issue was caused by the plaster plugin not correctly reading the texture resolution. I will close this issue as it is not directly related to Blockbench, but the issue in the plugin will be fixed with the next release.

**Closed by JannisX11** 2019-07-09 10:20 UTC

**Comment by MattTheBanana** [comment] 2021-06-03 17:03
This issue still occurs and I need help fixing it.
