### ISSUE TITLE
[Suggestion] Tabs

### ISSUE THREAD

**Issue by moskaoff** [JannisX11/blockbench#646] opened 2020-06-02 14:37 UTC
Being able to open more models at the same time
<img width="1445" alt="blockbench_concept_tabs" src="https://user-images.githubusercontent.com/19352571/83532984-4e899580-a4ef-11ea-82a6-2b0184206684.png">

**Comment by iWackyMinecraft** [comment] 2020-06-02 16:35
I think it would be better to have a full folder explorer on blockbench, which would make editing packs easy.

**Comment by moskaoff** [comment] 2020-06-02 17:58
Like bridges., it has tabs and a folder explorer, it would be really nice

**Comment by JannisX11** [comment] 2020-06-02 19:03
Duplicate of #411

**Closed by JannisX11** 2020-06-02 19:03 UTC
