### ISSUE TITLE
Texture not showing on mobile and cant edit texture

### ISSUE THREAD

**Issue by reyyan987** [JannisX11/blockbench#965] opened 2021-07-15 09:31 UTC
[!] Before you report an issue, check if if has already been reported. Also check if you are using the latest version of Blockbench.
[!] Prefix the title of your issue with [Issue] or [Suggestion]
[!] If you are having an issue, please press "Ctrl + Shift + i" and click on console. If there are any (red) error messages, please attach a screenshot of the console to your issue.

For issues, please provide the following informations:
- when I create a texture for my know model even with the template or simple texture it don't appears in the model and when I paint it don't show anything it is just transparent
![Screenshot_2021-07-14-18-31-06](https://user-images.githubusercontent.com/67619958/125765323-cb6a5410-77d1-4032-adae-553635df6325.jpeg) 
![Screenshot_2021-07-15-14-31-50](https://user-images.githubusercontent.com/67619958/125765551-4e9409eb-5bdd-457d-b6f8-6f4f3d5f7db1.jpeg)
![Screenshot_2021-07-15-14-31-57](https://user-images.githubusercontent.com/67619958/125765565-01d4e470-6076-4def-9ac0-5916a07b3473.jpeg)

For issues that are related to installation, opening/closing, import/export or other platform specific actions, please provide these informations: 
- Blockbench variant (Webapp/Desktop): webapp
- Operating System : KitKat Android

**Comment by JannisX11** [comment] 2021-07-17 18:51
Duplicate of #939

**Closed by JannisX11** 2021-07-17 18:51 UTC
