### ISSUE TITLE
[Issue] meshes can somehow exponentionally multiply their face number, causing lag & crashes when any operation is done on them

### ISSUE THREAD

**Issue by Azagwen** [JannisX11/blockbench#2096] opened 2023-11-15 12:14 UTC
### What are you trying to do, and what do you expect to happen?

I'm modeling something *that blockbench registers as being* rather large with a lot of polygons, and currently at UV unwrap phase.

### What happens instead?

Blockbench seems to be struggling a lot with UV edits. It refuses to display all faces, and moving any part of the UV map happens with a significant delay (1-2seconds). And occasionally crashes fully (screen turns a single uniform color and no input is recognized anymore).

The model I'm editing is *supposedly* made of 20656 faces, and Blockbench regularly drops under 20 FPS

This is very limiting for me, because I need to restart blockbench regularly and any changes I make to the UV map happens with enough delay to become tedious.

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Windows 10

### Installed Blockbench plugins

- CEM Template Loader 
- Geckolib Animation Utils 
- Shape Generator 
- Texture Stitcher 
- Cameras 
- Optimize 
- Plaster 
- MTools 
- Code View 
- Tint Preview 
- Mod Utils 
- Reference Models 
- Explorer

**Comment by Azagwen** [comment] 2023-11-15 12:16
PS: I also have footage of this happening, as I'm recording my modeling process with OBS (which could also affect performances, but the issue still occurs for me without OBS open)

**Comment by JannisX11** [comment] 2023-11-15 21:04
Do you know if your mesh is meant to have that many faces, or if it's another issue where it duplicates some faces? Does 20K sound like a realistic number for your model?

**Comment by Azagwen** [comment] 2023-11-15 21:39
> Do you know if your mesh is meant to have that many faces, or if it's another issue where it duplicates some faces? Does 20K sound like a realistic number for your model?

That's a really good point!
I'm actually not sure, this model definitely doesn't *look* like it's 20k faces.
I have a similar density model which is supposed to be mirrored later and that one is only saying 130 facces, so the model i'm editing should realistically be ~260 faces

**Comment by Azagwen** [comment] 2023-11-15 21:53
Blockbench VS Blender export data
![image](https://github.com/JannisX11/blockbench/assets/30528331/4ff31d30-b598-442f-9454-4cb2e48bb447)

![image](https://github.com/JannisX11/blockbench/assets/30528331/39557971-08e2-4db9-a7d6-5a6bbf01d3c9)

**Comment by Azagwen** [comment] 2023-11-16 11:47
Here's the model that claims to now have 40K faces instead of 327 (renamed from `.bbmodel` to `.json` because Github didn't wanna transfer it otherwise)
[bugged_skull.json](https://github.com/JannisX11/blockbench/files/13377194/bugged_skull.json)

**Comment by Azagwen** [comment] 2023-11-16 12:42
exporting to Blender and re-importing to Blockbench restaures the real face number on all elements

**Comment by Azagwen** [comment] 2023-11-16 12:53
exported and re-imported file (renamed from `.bbmodel` to `.json` as well for transfer): 
[working_skull.json](https://github.com/JannisX11/blockbench/files/13377831/working_skull.json)

**Comment by JannisX11** [comment] 2023-11-21 18:51
This turned out to be a single edge at the bottom of the skull that was duplicated.

**Comment by JannisX11** [comment] 2023-11-21 18:51
Duplicate of #2081

**Closed as not planned by JannisX11** 2023-11-21 18:51 UTC

**Comment by Azagwen** [comment] 2023-11-22 09:33
> This turned out to be a single edge at the bottom of the skull that was duplicated.

oh wow 🤣
Glad to know tho, will follow the original issue 👍
