### ISSUE TITLE
[Issue] Texture Extrusion is messing up

### ISSUE THREAD

**Issue by 3XH6R** [JannisX11/blockbench#147] opened 2018-10-18 04:19 UTC
Detailed description of your issue
Extruding textures is messing up values, elements, and uv when generating.

Blockbench variant (Webapp/Desktop)
Webapp and Desktop

Operating System
Windows 10 Home Version 1809

![image](https://user-images.githubusercontent.com/32020441/47130699-a8bce080-d24f-11e8-81ce-38f2125dcb51.png)
![image](https://user-images.githubusercontent.com/32020441/47130928-d6565980-d250-11e8-9918-d347f20b36f9.png)
![image](https://user-images.githubusercontent.com/32020441/47131096-b6736580-d251-11e8-9ba3-4be3e68da6ce.png)
![image](https://user-images.githubusercontent.com/32020441/47131186-3ef20600-d252-11e8-9683-b405ccc41442.png)

**Comment by JannisX11** [comment] 2018-10-18 09:53
Duplicate of #77

**Closed by JannisX11** 2018-10-18 09:53 UTC
