### ISSUE TITLE
[Issue] Transparency Issue (Viewing with Transparency)

### ISSUE THREAD

**Issue by Nediamail05** [JannisX11/blockbench#732] opened 2020-09-30 16:48 UTC
Hello! I was trying to make a animal in Blockbench (A frog in a bubble), and the bubble was transparent, but I couldn't see the frog (Except for some parts at different angles). When I looked at it from the back, then I could see everything, so I tried  to rotate it, but nothing changed (With the texture issue). Please fix this, I'm making profile pictures for my friends so I need to screenshot the model. Because I can't see past the transparency, the screenshot doesn't see through it either as well.
![IssueBad](https://user-images.githubusercontent.com/72153591/94715214-c4253700-0312-11eb-96ae-f8a810f91e08.png)
![IssueGood](https://user-images.githubusercontent.com/72153591/94715279-def7ab80-0312-11eb-9703-6b2789e9aabe.png)

This happens in all formats.

**Comment by AlexSerb-RU** [comment] 2020-10-27 16:49
Have you found a solution to the problem? I also encountered this...

**Comment by Nediamail05** [comment] 2020-10-27 22:48
No, I have not fixed it yet.

**Comment by JannisX11** [comment] 2020-11-11 15:04
Duplicate of #635

**Closed by JannisX11** 2020-11-11 15:04 UTC
