### ISSUE TITLE
[Update] Update the JPM format

### ISSUE THREAD

**Issue by ewanhowell5195** [JannisX11/blockbench#1699] opened 2022-12-20 22:14 UTC
### Detailed description of your suggestion

The JPM format needs to be updated to follow the proper JPM spec.

JPM models are identical to how the JEM submodels work, so yeah, simple update (hopefully)

**Comment by JannisX11** [comment] 2022-12-22 23:52
Duplicate of #456

**Closed by JannisX11** 2022-12-22 23:52 UTC
