### ISSUE TITLE
[Issue] Counter clockwise rotate rotates UV incorrectly

### ISSUE THREAD

**Issue by iWackyMinecraft** [JannisX11/blockbench#301] opened 2019-04-13 20:44 UTC
Counter clockwise rotate rotates UV incorrectly.
![image](https://user-images.githubusercontent.com/44243757/56085040-9231c380-5e45-11e9-86a2-62b8adac4cbe.png)
![issue](https://user-images.githubusercontent.com/44243757/56085069-053b3a00-5e46-11e9-8cf9-726602697b9c.gif)

 Blockbench 2.6.6

**Comment by JannisX11** [comment] 2019-06-07 18:43
Possible duplicate of #311

**Comment by JannisX11** [comment] 2019-06-07 19:51
Fixed in 2.6.7.

**Closed by JannisX11** 2019-06-07 19:51 UTC
