### ISSUE TITLE
Cannot open any model files on blockbench web app (I am unable to select any file to open)

### ISSUE THREAD

**Issue by melonmasteristaken** [JannisX11/blockbench#2013] opened 2023-08-26 03:05 UTC
### What are you trying to do, and what do you expect to happen?

I was trying to open a .JSON Minecraft bedrock model file but I couldn't as all of the files were not able to be selected 

### What happens instead?

Just can't open any file

### Model format in which the issue occurs

.json

### Blockbench variant

PWA

### Blockbench version

4.8.2 (pre release)

### Operating System

Android on Chrome browser pwa

### Installed Blockbench plugins

Entity wizard, block wizard, title generator

**Comment by JannisX11** [comment] 2023-08-26 14:36
Duplicate of #2004

**Closed by JannisX11** 2023-08-26 14:36 UTC
