### ISSUE TITLE
Importing Saved Project Issue

### ISSUE THREAD

**Issue by Ethan839** [JannisX11/blockbench#329] opened 2019-05-04 15:57 UTC
So I was working on a model, spent hours on it, saved the project, saved it once I was done, and exited out of the program.  So now when I try to import that saved project file (.bbmodel) it will not import correctly and gives me the same error message saying that it does not have the right model data. Is there another way to import this model file or is all hope lost?  Please get back to me as soon as possible..

Process of opening file in blockbench:
1. Run block bench
2. Import all textures for model
3. Hit file
4. Open Model
5. Click on model in folder
6. Error message "This file does not contain vaild model date"

![Screenshot_307](https://user-images.githubusercontent.com/35663784/57181578-4f1eab00-6e5b-11e9-8f1a-47ef4e607628.png)
![Screenshot_308](https://user-images.githubusercontent.com/35663784/57181579-4fb74180-6e5b-11e9-8cd3-e677344cf040.png)

**Comment by JannisX11** [comment] 2019-05-05 20:22
Change the file extension to .json, then open the model again.

**Comment by JannisX11** [comment] 2019-05-05 20:22
Duplicate of #324

**Closed by JannisX11** 2019-05-05 20:22 UTC
