### ISSUE TITLE
Loop cuts cause wireframe view to not show mesh accurately

### ISSUE THREAD

**Issue by Azagwen** [JannisX11/blockbench#1942] opened 2023-07-08 09:57 UTC
### What are you trying to do, and what do you expect to happen?

I was modeling a mesh object, and simply switched my viewport to wireframe mode to see through the model and reach mesh that was on the inside.

### What happens instead?

When I switched to wireframe to see through the object, instead of drawing lines on every edge, most of it disappeared. Leaving me with a mostly invisible model.

What the model looks like:
![image](https://github.com/JannisX11/blockbench/assets/30528331/fe64d4f6-b291-4139-a0a6-efc38d725f52)

What the model looks like in Wireframe
![Wireframe Views](https://github.com/JannisX11/blockbench/assets/30528331/8f1e1b10-7ca6-4354-9a0c-eb145ca55714)

This only occured to me once in the current latest release, I am unsure of the exact context in which it might occur

### Model format in which the issue occurs

Generic model

### Blockbench variant

Program

### Operating System

Windows 10

### Installed Blockbench plugins

CEM Template Loader
Geckolib anim utils
Mod utils
Code view
Reference models
Plaster
Optimize

**Comment by JannisX11** [comment] 2023-07-09 09:02
Did you merge any of the meshes? In that case it might be #1334

**Comment by Azagwen** [comment] 2023-07-09 09:59
> Did you merge any of the meshes? In that case it might be #1334

It was pretty early on for this model, so no, I hadn't merged anything together yet.
However I did have a large hidden box surrounding this mesh, don't know if that might have a role in this 🤔

**Comment by Azagwen** [comment] 2023-07-09 10:06
Managed to reproduce it, only a few loopcuts with these same conditions 

https://github.com/JannisX11/blockbench/assets/30528331/77aa4da9-bb0f-4167-8960-3b819512d568

**Comment by JannisX11** [comment] 2023-07-24 19:07
Duplicate of #1942

**Closed by JannisX11** 2023-07-24 19:07 UTC
Labels: bug
