### ISSUE TITLE
[Suggestion] Group Select inside the 3D Rendering Window.

### ISSUE THREAD

**Issue by Blaez-Dev** [JannisX11/blockbench#394] opened 2019-08-06 08:26 UTC
Being able to Select Elements on the 3D Rendering portion of the program instead of selecting one.
Shift+Right Click Drag would make a Box Selection tool similar to Paint Programs where it would select all elements inside the Selected area and allow you to group them making working on imports from cubik or other voxel programs easier as the elements are given non-descript names on export for some programs and it makes it difficult to select only the ones you want when the model itself can have potentially thousands of elements buried inside themselves for example.

**Comment by JannisX11** [comment] 2019-08-06 08:30
Duplicate of #180

**Closed by JannisX11** 2019-08-06 08:30 UTC
