### ISSUE TITLE
[Issue] I can't export with Optifine JPM | Problems with textures in JPM

### ISSUE THREAD

**Issue by Daminator4113** [JannisX11/blockbench#169] opened 2018-10-23 04:00 UTC
With the new version (2.0.0) I can't export with Optifine JPM (watch screenshot for error message : ![image](https://user-images.githubusercontent.com/43492665/47334336-d1e1d480-d686-11e8-88a2-a8da56958bae.png) )

With the previous version, when I'm exporting any models with Optifine JPM, sometimes, The textures coordinates/size aren't correct, and I need to fix them by myself. For example, if I use 64x64 textures, after exportating (or during editing), the textureSize argument are always in 16x16, same for coordinate (it cause these type of bug : ![image](https://cdn.discordapp.com/attachments/436665367058710528/484829099542446113/book.jpg) )

Blockbench variant : Webapp/Desktop
Operating System : Windows 10

**Comment by JannisX11** [comment] 2018-10-23 16:42
Duplicate of #144 
You can change the texture resolution in File > Project...

**Closed** 2018-10-23 16:43 UTC
