### ISSUE TITLE
[Suggestion] Support For Poly Mesh Bedrock Models

### ISSUE THREAD

**Issue by jacksomness** [JannisX11/blockbench#1270] opened 2022-01-29 00:41 UTC
It would be really amazing if blockbench had support for poly mesh models, even if we couldn't edit them in blockbench, because it would allow us to animate poly models using blockbench. It would also help people to make really complex addons and resource packs for bedrock edition because it is abhorrent to animate with polys. And even if it was a plugin, it would still be amazing if it had support.

**Comment by JannisX11** [comment] 2022-01-29 11:21
Duplicate of #555

**Closed by JannisX11** 2022-01-29 11:21 UTC
