### ISSUE TITLE
[Suggestion] Local alignment of rotation sphere

### ISSUE THREAD

**Issue by RishiMenon2004** [JannisX11/blockbench#633] opened 2020-05-14 08:15 UTC
The rotation sphere in local mode still shows the global type. So, I though like the move tool and scale tool has their local alignment with the cube, why doesn't the rotation sphere. It would rid the confusion of which axis to rotate when in local mode when it is rotated in another axis already. It would be really helpful

**Comment by JannisX11** [comment] 2020-05-14 08:35
Duplicate of #353

**Closed by JannisX11** 2020-05-14 08:35 UTC

**Comment by Techjar** [comment] 2020-07-18 00:06
I don't see how this is a duplicate. This appears to be a legitimate bug.
![](https://qimg.techjargaming.com/i/Ro9LeOCV.png)
I would expect the sphere to appear on the cube itself like the other tools.

**Comment by JannisX11** [comment] 2020-07-18 13:05
Rotations always occur around the pivot point of the element. Rotation space just changes the space that it is rotated in. "Local" space in this case is not strictly local, but it directly relates to the actual rotation values that you can see in the sidebar. Completely local rotation would not be possible because axes might overlap due to gimbal lock.
