### ISSUE TITLE
Blockbench not showing model

### ISSUE THREAD

**Issue by CPlayxs** [JannisX11/blockbench#2012] opened 2023-08-25 20:54 UTC
### What are you trying to do, and what do you expect to happen?

I open any model, or create a new one, and I should see a block or at least the grid.
![image](https://github.com/JannisX11/blockbench/assets/100153287/352c6fce-b801-432f-b985-3a3f4d06150d)

### What happens instead?

I open or create a model but nothing shows up, not even the grid, the cubes aren't hidden.

Only this error shows up on the console, I already tried reinstalling Blockbench, restarting my computer and restarting Blockbench, none of them worked.

![image](https://github.com/JannisX11/blockbench/assets/100153287/b715b2fc-cda6-4f23-8e17-c282a681a7aa)

### Model format in which the issue occurs

Generic

### Blockbench variant

Program

### Blockbench version

4.8.1

### Operating System

Fedora 38 Linux

### Installed Blockbench plugins

Discord RPC, cpm_plugin, CEM Template Loader, Minecraft Title Generator

**Comment by JannisX11** [comment] 2023-08-26 14:48
Duplicate of #1964

**Closed by JannisX11** 2023-08-26 14:48 UTC
