### ISSUE TITLE
Bug [item / Block Model] Interface display does not appear

### ISSUE THREAD

**Issue by KhrisMarin** [JannisX11/blockbench#945] opened 2021-06-30 03:57 UTC
Bug [item / Block Model] Interface display does not appear

I wanted to create a hammer mod but when customizing how it would look in the player interface, the image does not appear, there is no interface to guide you.

**Comment by JannisX11** [comment] 2021-06-30 07:11
Make sure you are using the latest version of Blockbench (3.9.1).

Duplicate of #940

**Closed by JannisX11** 2021-06-30 07:11 UTC
