### ISSUE TITLE
[Issue] Name sanitizing in outliner is not global

### ISSUE THREAD

**Issue by NyarlathoCotovoy** [JannisX11/blockbench#500] opened 2019-12-16 09:55 UTC
1. When naming a folder on russian language, the first letter of the name disappears.
2. Does not work: View> Interface scale> Reset scale.
OC: Windows

P.S. How to use toolbar customization? For example, I select "create animation" and it is shown to me: "hidden" how to make it appear on the toolbar?

**Comment by JannisX11** [comment] 2019-12-17 13:34
I cannot reproduce the second issue. Please double check that you are actually zoomed out or in before and if the issue still occurs, please create a new separate issue.

**Comment by JannisX11** [comment] 2019-12-17 22:51
Fixed in 3.2.1.

**Closed by JannisX11** 2019-12-17 22:51 UTC
